[project]
name = "WormTracer"
description = "WormTracer package"
authors = [
    { name = "Koyo Kuze" },
    { name = "Ukyo T. Tazawa" },
    { name = "Karin Suwazono" },
    { name = "Chung-Kuan Chen", email = "b97b01045@gmail.com" },
    { name = "Yu Toyoshima" },
    { name = "Yuichi Iino", email = "iino@bs.s.u-tokyo.ac.jp" },
]
dynamic = ["version", "readme"]
license = { file = "LICENSE" }
requires-python = ">=3.9"
dependencies = [
    "numpy<2",
    "opencv-python-headless",
    "matplotlib",
    "Pillow",
    "scikit-image",
    "scipy",
    "pyyaml",
    "roifile[all]>=2020.11.28",
    "torch",
    "torchvision",
    "h5py",
]

[project.scripts]
wormtracer = "WormTracer.__main__:main_wrapper"

[project.optional-dependencies]
gui = [
    "imageio[ffmpeg]>=2.37.2",
    "napari-wormtracer @ git+https://github.com/lycantrope/napari-wormtracer.git",
    "napari[all]>=0.5.6",
]

[build-system]
requires = ["setuptools>=80", "wheel", "setuptools_scm[simple]>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
readme = { file = ["README.md"] }

[tool.setuptools_scm]
version_file = "src/WormTracer/_version.py"


[tool.ruff.lint]
extend-select = ["I001"]
ignore = ["F401", "F405"]

[tool.uv.sources]
napari-wormtracer = { git = "https://github.com/lycantrope/napari-wormtracer" }

[dependency-groups]
dev = []
