[project]
name = "WormTracer"
description = "WormTracer package"
authors = [
    { name = "Koyo Kuze" },
    { name = "Ukyo T. Tazawa" },
    { name = "Karin Suwazono" },
    { name = "Chung-Kuan Chen", email = "b97b01045@gmail.com" },
    { name = "Yu Toyoshima" },
    { name = "Yuichi Iino", email = "iino@bs.s.u-tokyo.ac.jp" },
]
dynamic = [ "version", "readme" ]
requires-python = ">=3.8"
dependencies = [
    "numpy<2",
    "opencv-python-headless",
    "matplotlib",
    "Pillow",
    "scikit-image",
    "scipy",
    "pyyaml",
    "roifile[all]>=2020.11.28",
]
license = { file = "LICENSE" }

[project.scripts]
wormtracer = "WormTracer.__main__:main"

[build-system]
requires = [ "setuptools", "wheel" ]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = { attr = "WormTracer.__version__" }
readme = { file = [ "README.md" ] }

[tool.ruff.lint]
extend-select = [ "I001" ]
ignore = [ "F401", "F405" ]
