# parameters

local_time_difference: 9

start_T: 0
end_T: 0
rescale: 1
Tscale: 1

continuity_loss_weight: 10000
smoothness_loss_weight: 100000
length_loss_weight: 50
center_loss_weight: 50

plot_n: 100
epoch_plus: 1500
speed: 0.05
lr: 0.05
body_ratio: 90
judge_head_method: frequency

# display options

num_t: 5
ShowProgress: False
SaveProgress: False
show_progress_freq: 200
save_progress_freq: 50
save_progress_num: 50

SaveCenterlinedWormsSerial: True
SaveCenterlinedWormsMovie: True
SaveCenterlinedWormsMultitiff: True

